apiVersion: v1
kind: ServiceAccount
metadata:
  name: mypodserviceaccount
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: read-secrets-service-account@project-id.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod-new
  namespace: default
spec:
  serviceAccountName: mypodserviceaccount
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: mypod
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
      - mountPath: "/var/secrets"
        name: mysecret
  volumes:
  - name: mysecret
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "app-secrets"