services: 
  vault_node_1: 
    image: vault:1.13.3 
    container_name: vault_node_1 
    ports: 
      - "8200:8200" 
    environment: 
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200" 
      VAULT_DEV_ROOT_TOKEN_ID: mytoken 
      VAULT_LOG_LEVEL: debug 
    volumes: 
      - ./haproxy.cfg:/haproxy.cfg
      - ./port-forward.sh:/port-forward.sh