apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aesgcm:
          keys:
            - name: key1
              secret: sfzsUFbNX5NOyPzDrRGvsRcBagO/0h5ifxTMKX5wfDE=
      - identity: {}

