apiVersion: v1
kind: Pod
metadata:
  name: print-env-pod
spec:
  containers:
    - name: print-env-pod
      image: busybox
      command: ["/bin/sh","-c"]
      args: ["echo $key|md5sum"]
      envFrom:
        - secretRef:
            name:  aes-key
  restartPolicy: Never