apiVersion: v1
kind: Pod
metadata:
  name: print-env-pod
spec:
  containers:
    - name: print-env-pod
      image: busybox
      command: ["sh", "-c", "env"]
      envFrom:
        - secretRef:
            name:  aes-key
  restartPolicy: Never